---
title: "Vignette for RNAsense package"
output: rmarkdown::html_vignette
fig_width: 8 
fig_height: 6
vignette: >
  %\VignetteIndexEntry{Put the title of your vignette here}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, echo = FALSE}
require(ggplot2)
require(parallel)
require(NBPSeq)
require(qvalue)
```

```{r read data}
startTime <- Sys.time() # get start time
analyzeConditions <- c("WT", "MZsox")
ini <- TRUE

mypath <- paste0(getwd(), "/Zv11_WTB1-4_sox")
files <- list.files(path = mypath, recursive = TRUE, include.dirs = TRUE)
files <- files[which(grepl(".tabular", files))]
for(file in files){
  nametag <- gsub("\\[|\\]", "", strsplit(strsplit(file, "-")[[1]][2], ".tabular")[[1]][1])
  replicate <- strsplit(nametag, "hpf")[[1]][2]
  condition_time <- strsplit(nametag, "hpf")[[1]][1]
  for(cond in analyzeConditions) {condition_time <- sub(cond, paste0(cond,"_"), condition_time)}
  condition <- paste0(condition_time, "_", replicate)
  if(grepl(analyzeConditions[1], nametag) | grepl(analyzeConditions[2], nametag)){
    if(ini){
      temp <- as.data.frame(read.table(paste0(mypath, "/",file), sep="\t"))
      genenames <- read.table(paste0(mypath, "/",file), sep="\t")[,2]
      colnames(temp) <- c("name", "genename", condition)
      ini <<- FALSE
      mydata <- temp
    } else {
      temp <- as.data.frame(read.table(paste0(mypath, "/",file), sep="\t")[,3])
      colnames(temp) <- condition
      mydata <- cbind(mydata,temp)
    }
  }
}
# mydata is data in standard format
thCount <- 100
nrcores <- 4

vec2Keep <- which(sapply(1:dim(mydata)[1],function(i) !Reduce("&",mydata[i,3:dim(mydata)[2]]<thCount)))
mydata <- mydata[vec2Keep,]
genenames <- genenames[vec2Keep]
times <- sort(unique(as.numeric(do.call(rbind,strsplit(names(mydata)[-c(1,2)], "_"))[,2])))

# apply fold change detection
resultFC <- RNAsense:::getFC(dataset = mydata, myanalyzeConditions = analyzeConditions, cores = nrcores, mytimes = times)

# generate and output vulcano plot
ggplot(subset(resultFC, !is.na(FCdetect)), aes(x=logFoldChange, y=-log10(pValue), color=FCdetect)) + xlab("log2(Fold Change)") + geom_point(shape=20)

# apply switch detection
resultSwitch <- RNAsense:::getSwitch(dataset = mydata, cores = nrcores)
# collect results
resultCombined <- RNAsense:::combineResults(resultSwitch, resultFC)

RNAsense:::plotSSGS(resultCombined, c(2.5,3,3.5,4,4.5,5,5.5))

#Output gene switch tables
#RNAsense:::outputGeneTables(resultCombined)

endTime <- Sys.time() # get end time
cat(paste0("Finished with Running Time: ", round(as.numeric(as.difftime(endTime-startTime, units = "mins")), digits = 2), " minutes")) 
```
